blank_issues_enabled: false
contact_links:
  - name: Group
    url: mqqapi://card/show_pslcard?src_type=internal&version=1&uin=1028233124&card_type=group&source=qrcode
    about: Our Telegram Group 
  - name: smart-question
    url: https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md
    about: READ BEFORE YOU ASKING ANY QUESTION
