name: Feature request/功能请求
description: Feature request./提出你想要的功能。
labels: [Feature]
title: "[功能请求] "
body:
  - type: markdown
    attributes:
      value: |
        感谢您给 PPHelper 提出建议！
        为了使我们更好地帮助你，请提供以下信息。

  - type: "input"
    id: version
    attributes:
      label: "皮皮搞笑版本/ZuiyouLite Version"
      description: "皮皮搞笑版本/ZuiyouLite Version"
    validations:
      required: true

  - type: textarea
    id: why
    attributes:
      label: 为什么你认为需要此功能
    validations:
      required: true

  - type: textarea
    id: related-feature
    attributes:
      label: 联系到哪些已经存在的bug或者功能
      description: 如果没有留空即可
    validations:
      required: false

  - type: textarea
    id: details
    attributes:
      label: 具体功能需要/Specific features require
    validations:
      required: true
