/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_lliiooll_pphelper_ffmpeg_FFmpeg */

#ifndef _Included_cn_lliiooll_pphelper_ffmpeg_FFmpeg
#define _Included_cn_lliiooll_pphelper_ffmpeg_FFmpeg
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_lliiooll_pphelper_ffmpeg_FFmpeg
 * Method:    runCmd
 * Signature: (I[Ljava/lang/String;Lcn/lliiooll/pphelper/ffmpeg/FFmpegCallBack;)V
 */
JNIEXPORT void JNICALL Java_cn_lliiooll_pphelper_ffmpeg_FFmpeg_runCmd
  (JNIEnv *, jclass, jint, jobjectArray, jobject);

/*
 * Class:     cn_lliiooll_pphelper_ffmpeg_FFmpeg
 * Method:    initNative
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_cn_lliiooll_pphelper_ffmpeg_FFmpeg_initNative
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
